# @package _group_
birdview:
  module: birdview.chauffeurnet
  width_in_pixels: 192
  pixels_ev_to_bottom: 40
  pixels_per_meter: 5.0
  history_idx: [-16, -11, -6, -1]  # [-16, -11, -6, -1]
  scale_bbox: true
  scale_mask_col: 1.0
  neglect_rl_stop: false
speed:
  module: actor_state.speed
control:
  module: actor_state.control
velocity:
  module: actor_state.velocity

gnss:
  module: navigation.gnss
#central_rgb:
# module: camera.rgb
# fov: 90
# width: 900
# height: 256
# location: [1.0, 0.0, 1.5]
# rotation: [0.0, 0.0, 0.0]
route_plan:
  module: navigation.waypoint_plan
  steps: 20
traffic_light:
  module: object_finder.traffic_light_new
stop_sign:
  module: object_finder.stop_sign
  distance_threshold: 10.0
