# @package _group_
entry_point: agents.rl_vlm.models.sac:SACVlm
kwargs:
  learning_rate: 1e-4
  buffer_size: 150_000  # compress_size (192, 192)
  learning_starts: 1024 # 1024
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  optimize_memory_usage: false  # DictReplayBuffer doesn't support it
  ent_coef: "auto" #"auto_0.1"  # 0.01
  target_update_interval: 1
  target_entropy: "auto"
  tensorboard_log: null
  verbose: 1
  device: "auto"
  use_vlm: &use_vlm 'r_clip'
  imitation_coef: 0.1
  replay_buffer_class: agents.rl_vlm.models.replay_buffer:DictReplayBufferVlm
  replay_buffer_kwargs:
    handle_timeout_termination: true
    use_vlm: *use_vlm
  policy_kwargs:
    features_extractor_class: agents.rl_vlm.models.torch_layers:LiteXtMaCNN
    features_extractor_kwargs:
      features_dim: 256
      states_neurons: [256,256]
    use_sde: false