# @package _group_
entry_point: agents.rl_vlm.models.drqv2_policy:DrQv2Policy
kwargs:
  policy_head_arch: [256, 256]
  qf_head_arch: [256, 256]
  features_extractor_entry_point: agents.rl_vlm.models.torch_layers:XtMaCNN
  features_extractor_kwargs:
    states_neurons: [256,256]
