# @package _group_
entry_point: agents.rl_vlm.models.sac_policy:SACPolicy
kwargs:
  policy_head_arch: [256, 256]
  qf_head_arch: [256, 256]
  features_extractor_entry_point: agents.rl_vlm.models.torch_layers:XtMaCNN
  features_extractor_kwargs:
    states_neurons: [256,256]
  distribution_entry_point: agents.rl_vlm.models.distributions:SquashedDiagGaussianDistribution
  distribution_kwargs:
    log_std_init: -2.0
    action_dependent_std: true